import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

import { Orbitron } from "next/font/google";
import Contact from "@/components/page/landing/contact";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-orbitron",
});

export const metadata: Metadata = {
  title: "Polk Roadside",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">



      <body
        className={orbitron.variable}
      >
        <Navbar />
        {children}
        <Contact/>
        <Footer />
      </body>
    </html>
  );
}
